version: "3.3" # Specify a version

services:
  nirvana-bot:
    build: .
    ports:
      - "4050:4050"
    networks:
      - nirvana-network

  redis-server:
    image: "redis:7.2.5"
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - nirvana-network

  proxy:
    container_name: discord-proxy
    image: ghcr.io/twilight-rs/http-proxy:metrics
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
    environment:
      - RUST_LOG=warn,info,debug,trace
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - nirvana-network

networks:
  nirvana-network:
    driver: bridge
